<<<<<<< HEAD
version: "2"
services:
    apka:
        build: .
        ports:
            - "80:80"
=======
version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: lastsicarius/zacynam:cz.1
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
>>>>>>> 313f45766c02a4fd79728bc2b4bf1c915a8d9aea
